# Development environment

FROM python:3.10-slim

# MySQL 관련 패키지 설치
RUN apt-get update && apt-get install -y \
    default-libmysqlclient-dev \
    libmariadb-dev \
    libmariadb3 \
    build-essential \
    pkg-config \
    netcat-openbsd  # Netcat OpenBSD 버전 설치

WORKDIR /app

COPY requirements-dev.txt .
RUN pip install --no-cache-dir -r requirements-dev.txt

# 애플리케이션 파일 복사
COPY . .


# 환경 변수 설정
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# 개발 환경에서는 Gunicorn 대신 Django 개발 서버 실행
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
